### ISSUE TITLE
Prepare Release v0.6.0

### ISSUE THREAD

**Issue by bhilburn** [bhilburn/powerlevel9k#371]
Hey all -

We have a ton of new features already in `next`, and a bunch more on the way. The most major development that is ongoing, right now, is @dritter's work on the async branch. We have ~80 unique cloners a day, which means we have thousands of users out there. What I would like to do is get a new release out that includes a bunch of our latest improvements before @dritter finishes the async branch, and then have the v0.6.0 --> v0.7.0 upgrade include the async changes.

Here's what I would like to have done for the v0.6.0 release:

**HIGH Priority:**
- [ ] Context improvements: #335 
- [x] SSH detection for context segment :#336 
- [ ] new screenshot #370 
- [x] hdd_usage segment #378  
- [x] public IP segment #368 
- [x] changelog #363 
- [x] logo #367 

**Normal Priority:**
- [ ] svn icon fix #312 
- [ ] package.json truncation: #350 
- [ ] dir segment improvements #353 
- [ ] python virtualenv improvement #345 

The last three are on-going, and I'm not worried about finishing them out. @V1rgul is helping with #350, @rjorgenson is working on #368, and @shibumi is  working on #335 / #336. I believe that #312, #352, #353, and #345 have stalled, though. If anyone is interested in tackling one and finishing it up, please respond and claim it! 

Thanks, everyone, for making P9k the best ZSH theme out there =)

**Comment by dritter** [comment]
IMHO, release planning would bei nice thing to try out githubs brand new "project" feature. :) Would you mind trying that? That would bei awesome.

**Comment by bhilburn** [comment]
Frankly, I forgot it existed. I'll give it a go...

**Comment by bhilburn** [comment]
Okay, I made a project out of this: https://github.com/bhilburn/powerlevel9k/projects/1

One of the issues with the Project feature, though, is that there doesn't appear to be a way to leave comments on the specific cards. If you want to claim one of the issues (in the list above), either assign the bug to yourself or comment here. Thanks!

**Comment by bhilburn** [comment]
I'm going to tag v0.6.0 once #385 and #410 are resolved.

**Comment by bhilburn** [comment]
The release is out!

**Comment by brianjking** [comment]
@bhilburn Is the correct method to upgrade when using Oh-My-Zsh to simply do the following:

* `cd oh-my-zsh/custom/themes/powerlevel9k`
* `git pull`

If not, what is the proper method to grab a specific release as right now it's just pulling from `master`?

Thanks!

**Comment by dritter** [comment]
@brianjking in short: Usually yes. :) Btw. after that you have to open a new shell.
